# Generated by Django 6.0.4 on 2026-04-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
