# Generated by Django 6.0.4 on 2026-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='department',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='priority',
        ),
        migrations.AddField(
            model_name='annonce',
            name='categorie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='annonce',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annonce',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annonce',
            name='ville',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
