# Generated by Django 6.0.4 on 2026-04-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_rename_created_at_annonce_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='description',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='ville',
        ),
        migrations.AddField(
            model_name='annonce',
            name='contenu',
            field=models.TextField(default=''),
        ),
    ]
