# Generated by Django 6.0.4 on 2026-04-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_remove_annonce_categorie_remove_annonce_description_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.department'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
